name: Sheiks & Bishops Staging

on:
    push:
        branches:
            - staging

permissions:
    contents: write

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Copy HTML pages to repository root
              run: cp pages/*.html .

            - name: Commit changes
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  git add *.html

                  if git diff --cached --quiet; then
                    echo "No changes to commit"
                  else
                    git commit -m "Copy HTML pages to repository root"
                    git push
                  fi
